### ISSUE TITLE
v45 - nested dependency overrides have changed

### ISSUE THREAD

**Issue by mashaal** [postui/esm.sh#101]
When specifying a dep query, the dep seems to only effect the first level of imports?

Example:
https://esm.sh/wouter?deps=react@18.0.0-alpha-edfe50510-20210823 -- which imports this file... [v45](https://cdn.esm.sh/v45/wouter@2.7.4/X-ZGVwczpyZWFjdEAxOC4wLjAtYWxwaGEtZWRmZTUwNTEwLTIwMjEwODIz/es2021/wouter.js)

This file is correctly dep'd, but it includes an import (first import of the file) to https://cdn.esm.sh/v45/wouter@2.7.4/es2021/use-location.js -- which does not have its react dep overwritten `/v45/react@17.0.2/es2021/react.js`

This seems to have changed from 44 to 45, as I have a local self hosted instance of 44 running. Here is the example, and the imports seem to be resolved correctly here... [v44](https://exx.sh/v44/wouter@2.7.4/X-ZGVwczpyZWFjdEAxOC4wLjAtYWxwaGEtZWRmZTUwNTEwLTIwMjEwODIz/es2021/wouter.js)

**Comment by ije** [comment]
@mashaal thanks, i will fix this asap! v45 has cancel bundling for internal modules of a package, you can use `?bundle` as a workaround.

**Comment by ije** [comment]
@mashaal fixed in v46, thanks
