### ISSUE TITLE
Duplicate type definition "esm.sh" and "cdn.esm.sh"

### ISSUE THREAD

**Issue by kamekyame** [postui/esm.sh#104]
I'm using Deno to make a React app.

https://esm.sh/recharts@2.0.8 refers to "https://esm.sh/v46/@types/react@17.0.19/index.d.ts" as part of the react type definition.
This is the type definition "https://cdn.esm.sh/v46/@types/react@17.0.19/index.d.ts" such as https://esm.sh/react@17.0.2 It will be duplicated.

**Comment by ije** [comment]
@kamekyame thanks, i just fix it. (the dts transformer is using no-cdn domain that is conflict with `X-Typescript-Types`)
