### ISSUE TITLE
simple-git package not working under target=deno

### ISSUE THREAD

**Issue by frodri** [postui/esm.sh#105]
Reproducible on Deno version v1.13.2, using the following:

```javascript
import git from "https://esm.sh/simple-git?target=deno";
```

I believe the polyfill for child_process is up on std/node. Would it be possible to use it for adding esm.sh support on the deno target?

**Comment by ije** [comment]
@frodri i just added child_process polyfill using `std/node/child_process.ts` in **v47**, but i am not sure if it works, please try again, thanks!

**Comment by frodri** [comment]
I see the polyfill in the script now, so that's good.  👍 Would the changes to @types/node for child_process need to be updated on the CDN, if the @types/node repo made recent changes to the typings though?

**Comment by ije** [comment]
no worries, we have a ployfll for `@types/node`, see https://github.com/postui/esm.sh/blob/master/embed/types/node.ns.d.ts

**Comment by frodri** [comment]
Got it. I think I can get you a PR with the new child_process typings into node.ns.d.ts. I do not know, though, which one of the 2 tsconfigs from deno-std (strict-ts44.tsconfig.json or browser-compat.tsconfig.json) would work best for esm.sh's 'deno' target. Some more help in that regard would be appreciated.

**Comment by ije** [comment]
@frodri coool, but why we need this types for child_process module? since deno can get the deps' types via esm.sh. A simple node types replacement can avoid deno download ton of DTS files via esm.sh.  IMO the types is great for editor like vscode, but deno shouldn't take everything types from npm. besides deno will diable types checking by default in the future.

**Comment by frodri** [comment]
@ije Oh. I didn't know about the incoming Deno type check default. In that case, we're all good. 👍
