### ISSUE TITLE
esm.sh does not have git binary

### ISSUE THREAD

**Issue by hazae41** [postui/esm.sh#12]
For example, when trying to compile WalletConnect, it throws "Could not find the binary git"
https://github.com/WalletConnect/walletconnect-monorepo/issues/405

Is it possible to have git?

**Comment by shadowtime2000** [comment]
I am confused on why building wallet connect requires `git`. Maybe esbuild does something with the `gitHead` in the `package.json`.

**Comment by hazae41** [comment]
The issue seems fixed, it works now, even with the same module version

**Comment by ije** [comment]
thanks, i'm think it was fixed by the new esbuild.
