### ISSUE TITLE
Unable to bundle graphql

### ISSUE THREAD

**Issue by FallingSnow** [postui/esm.sh#14]
```js
INFO Download https://esm.sh/graphql • https://esm.sh/graphql?target=es2018&dev
error: Uncaught (in promise) Error: Download https://esm.sh/graphql: Download https://esm.sh/graphql: 500 - Internal Server Error
```

When traversing to `https://esm.sh/graphql?target=es2018&dev` you get
```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: \"graphql\" has already been declared");
export default null;
```

**Comment by shadowtime2000** [comment]
Looks like it is partially a problem with the `graphql` package and how they wrote it

**Comment by FallingSnow** [comment]
Esbuild seems to have no problem bundling it locally.

app.tsx:
```js
import * as Graphql from "graphql";
console.log(Graphql)
```

```bash
$ yarn add esbuild graphql
$ node_modules/.bin/esbuild app.tsx --bundle --outfile=out.js
```

**Comment by shadowtime2000** [comment]
Strange...

**Comment by shadowtime2000** [comment]
Maybe ESM is using an older version of esbuild?

**Comment by ije** [comment]
@FallingSnow thanks, i will figure it out what happened.

**Comment by FallingSnow** [comment]
I've worked out that the input going into esbuild is incorrect. Here is effectively the cause of the compiler fail:
```ts
export const { version,versionInfo,graphql, ....... } = graphql;
```

Note this is passed in at https://github.com/postui/esm.sh/blob/c61d1a05462a1d413f2b69797093e3ae54de7912/server/build.go#L465

An example of what the compiler is trying to compile:
```js
const graphql = {
	graphql: "test"
};
export const { graphql } = graphql;
export default graphql;
```
Which results in
```js
$ node script.js
file:///tmp/script.js:4
export const { graphql } = graphql;
               ^

SyntaxError: Identifier 'graphql' has already been declared
    at Loader.moduleStrategy (node:internal/modules/esm/translators:145:18)
    at async link (node:internal/modules/esm/module_job:47:21)
```

Now to find out why esbuild is being passed this.

**Comment by ije** [comment]
@FallingSnow thanks for the details, it is vary useful for me, and i just fixed it! please try it agian: https://esm.sh/graphql.

**Comment by FallingSnow** [comment]
Great, it's working great! I'm finally only using `esm.sh` and denoland.
