### ISSUE TITLE
Exports not exported for graphql-request

### ISSUE THREAD

**Issue by FallingSnow** [postui/esm.sh#15]
Esm.sh does not correctly export non default exports. When using skypack it does.

Take graphql-request for example.
Graphql-request does export a gql function.
https://github.com/prisma-labs/graphql-request/blob/5b233c5658e65ed0d98cf8bff50beec413f399b9/src/index.ts#L223

Using skypack:
```js
import request, {gql} from "https://cdn.skypack.dev/graphql-request";
console.log(gql); // function...
```

Using esm.sh:
```js
import request, {gql} from "https://esm.sh/graphql-request";
console.log(gql); // undefined
```

What's strange is when you download the esm.sh bundle (https://cdn.esm.sh/v14/graphql-request@3.4.0/esnext/graphql-request.js) it contains the following at the end. Which clearly contains gql...
```js
...
export {
    jt as ClientError, At as GraphQLClient, It as
    default, Bt as gql, _t as rawRequest, Ft as request
};
```

**Comment by shadowtime2000** [comment]
The skypack example you gave doesn't seem to run properly
![image](https://user-images.githubusercontent.com/66655515/104401788-c0a46d00-5509-11eb-8c14-ae455e419c9c.png)
The fact that it is importing `/language/printer` instead of `/language/printer.js` is a little strange...

**Comment by shadowtime2000** [comment]
I was looking through the bundle (yes I know it's not that good of a thing to do) but it seems `Bt` is never defined. `bt` is but JavaScript references are case sensitive I believe. Could that be the case?

**Comment by FallingSnow** [comment]
Ok... oddly enough this does work though.

```js
import {graphql} from "https://cdn.skypack.dev/graphql";
import request, {gql} from "https://cdn.skypack.dev/graphql-request";
console.log(graphql, gql);
```

I can upload a test repo if you'd like.

**Comment by FallingSnow** [comment]
Ok you're right. In fact none of the others are defined either (At, _t, Ft, jt)...

**Comment by FallingSnow** [comment]
I guess what's next is to try a local esbuild example.

**Comment by FallingSnow** [comment]
Local esbuild does work correctly.

app.ts
```js
import {gql} from "graphql-request";
console.log(gql);
```

```bash
$ yarn add esbuild graphql-request
$ ./node_modules/.bin/esbuild app.ts --bundle --platform=node --outfile=out.js
$ node out.js
[Function: gql2]
```

**Comment by ije** [comment]
```js
import * as Request from "https://esm.sh/graphql-request";
console.log(Request);
```

i got the output: 

```bash
Module {
  ClientError: undefined,
  GraphQLClient: undefined,
  default: [Function: Pe],
  gql: undefined,
  rawRequest: undefined,
  request: undefined,
  [Symbol(Symbol.toStringTag)]: "Module"
}
```

seems it is the esbuild issue, i'm not sure what happened, will check the esbuild api later, thanks @FallingSnow

**Comment by shadowtime2000** [comment]
Yeah, seems to be a problem with the esbuild minifier. We should probably file a bug report there

**Comment by ije** [comment]
@FallingSnow can you please try `./node_modules/.bin/esbuild app.ts --bundle --platform=web --outfile=out.js`

**Comment by FallingSnow** [comment]
![Screenshot from 2021-01-12 21-36-07](https://user-images.githubusercontent.com/2512197/104410961-45998180-551e-11eb-9a39-cfbe405d975d.png)
Export is good still. Btw `--platform=browser` is the correct flag. Are we using the same esbuild version?
```
$ ./node_modules/.bin/esbuild --version
0.8.31
```

**Comment by ije** [comment]
<img width="649" alt="Screenshot 2021-03-30 at 03 02 58" src="https://user-images.githubusercontent.com/2883484/112886406-7d1ecf80-9104-11eb-89aa-074101737459.png">

**Comment by ije** [comment]
fixed
