### ISSUE TITLE
Module exports { default, __esModule } 

### ISSUE THREAD

**Issue by hazae41** [postui/esm.sh#17]
When importing the default export from WalletConnect

```typescript
import WalletConnect from "https://esm.sh/@walletconnect/web3-provider"

console.log(WalletConnect)
```

Which is a class in my editor

![Capture](https://user-images.githubusercontent.com/4405263/105909182-823da080-6027-11eb-8450-551100a5888b.PNG)
 
However, when deploying (aleph dev) I get the following object instead

![Capture](https://user-images.githubusercontent.com/4405263/105909338-b6b15c80-6027-11eb-820d-967b7617bfd7.PNG)

**Comment by shadowtime2000** [comment]
I think this is kind of expected behaviour, has something to do with the conversion of CJS -> ES though I think this is based on the build system of WalletConnect instead of on ESM's side

**Comment by hazae41** [comment]
Thanks, any idea how I can reconciliate my editor and the browser?

**Comment by hazae41** [comment]
I did this workaround

```typescript
import WalletConnectModule from "https://cdn.esm.sh/v15/@walletconnect/web3-provider@1.3.4/esnext/web3-provider.js"
import WalletConnectProvider from "https://cdn.esm.sh/v15/@walletconnect/web3-provider@1.3.4/dist/cjs/index.d.ts"

const WalletConnect: typeof WalletConnectProvider = WalletConnectModule.default
```

**Comment by shadowtime2000** [comment]
Yup, it has to do with the fact that WalletConnect isn't shipping ES modules and instead they are using Webpack + TS to convert their ES source code into CJS which is published. This causes `export default` to be transformed to `exports.default` which isn't actually a proper conversion though. @hazae41 I'd recommend you open an issue on their repo.

**Comment by hazae41** [comment]
Okay thanks
