### ISSUE TITLE
Cannot Import Submodule CSS

### ISSUE THREAD

**Issue by akash-joshi** [postui/esm.sh#2]
Hey guys, I was trying to use ant.design components with alephjs, which recommends using esm.sh for npm imports. I tried importing the CSS file: https://esm.sh/antd/dist/antd.css, however it throws a 500 error.

Is importing CSS beyond the intended usage of esm.sh ? 

Do let me know. Thanks

**Comment by ije** [comment]
@akash-joshi fixed, please try again!

**Comment by akash-joshi** [comment]
Thanks a lot. Closing this issue
