### ISSUE TITLE
Certificate Issue with esm.sh?

### ISSUE THREAD

**Issue by jeffrey-l-turner** [postui/esm.sh#20]
I'm trying:
```deno cache --reload https://esm.sh/react@17.0.0```

and get:

```Download https://esm.sh/react@17.0.0
Sending fatal alert BadCertificate
error: error sending request for url (https://esm.sh/react@17.0.0): error trying to connect: invalid certificate: UnknownIssuer```

Is there a certificate issue on the server?

**Comment by ije** [comment]
the server is using let's encrypt tls

**Comment by ije** [comment]
the server is using let's encrypt tls, i not sure what happened, can you open it in the browser?

**Comment by jeffrey-l-turner** [comment]
It turned out to be a proxy issue with my "enterprise" Mac... I really hate these man in the middle TLS/SSLHTTPS proxies -- I think they represent huge security threats. Closing this.
