### ISSUE TITLE
@types/prop-types build failed

### ISSUE THREAD

**Issue by hazae41** [postui/esm.sh#21]
Hey, I try to build my website using aleph 3.0 alpha 8, but the following file failed to build 

https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts

```typescript
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: The constant \"nominalTypeHack\" must be initialized");
export default null;
```

> 11:55:24 PM 02/08/2021: INFO Aleph server config loaded from aleph.config.js
11:55:24 PM 02/08/2021: INFO Building...
11:55:25 PM 02/08/2021: INFO Download https://esm.sh/react@17.0.1
11:55:26 PM 02/08/2021: INFO Download https://cdn.esm.sh/v15/react@17.0.1/esnext/react.js
11:55:26 PM 02/08/2021: INFO Download https://deno.land/x/aleph@v0.3.0-alpha.8/mod.ts
11:55:27 PM 02/08/2021: INFO Download https://deno.land/x/aleph@v0.3.0-alpha.8/framework/react/hooks.ts
11:55:27 PM 02/08/2021: INFO Download https://deno.land/x/aleph@v0.3.0-alpha.8/framework/react/context.ts
11:55:27 PM 02/08/2021: INFO Download https://deno.land/x/aleph@v0.3.0-alpha.8/framework/react/util.ts
11:55:27 PM 02/08/2021: INFO Download https://deno.land/x/aleph@v0.3.0-alpha.8/framework/react/error.ts
11:55:28 PM 02/08/2021: INFO Download https://esm.sh/@ethersproject/providers
11:55:28 PM 02/08/2021: INFO Download https://cdn.esm.sh/v15/@ethersproject/providers@5.0.21/esnext/providers.js
11:55:30 PM 02/08/2021: INFO Download https://cdn.esm.sh/v15/_process_browser.js
11:55:31 PM 02/08/2021: INFO Download https://esm.sh/react-dom@17.0.1
11:55:31 PM 02/08/2021: INFO Download https://cdn.esm.sh/v15/react-dom@17.0.1/esnext/react-dom.js
11:55:32 PM 02/08/2021: INFO Download https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts
11:55:33 PM 02/08/2021: WARN Download https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts failed, retrying...
11:55:34 PM 02/08/2021: WARN Download https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts failed, retrying...
11:55:35 PM 02/08/2021: WARN Download https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts failed, retrying...
11:55:36 PM 02/08/2021: WARN Download https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts failed, retrying...
11:55:37 PM 02/08/2021: WARN Download https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts failed, retrying...
11:55:37 PM 02/08/2021: WARN Download https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts failed, retrying...
11:55:38 PM 02/08/2021: WARN Download https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts failed, retrying...
11:55:39 PM 02/08/2021: WARN Download https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts failed, retrying...
11:55:39 PM 02/08/2021: WARN Download https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts failed, retrying...
11:55:40 PM 02/08/2021: error: Uncaught (in promise) Error: Internal Server Error
11:55:40 PM 02/08/2021: return Promise.reject(new Error(resp.statusText));
11:55:40 PM 02/08/2021: ^
11:55:40 PM 02/08/2021: at app.ts:1141:35
11:55:40 PM 02/08/2021: at async Application.fetchDependency (app.ts:1139:24)
11:55:40 PM 02/08/2021: at async Application.compile (app.ts:800:25)
11:55:40 PM 02/08/2021: at async Application.compile (app.ts:983:22)
11:55:40 PM 02/08/2021: at async Application.compile (app.ts:983:22)
11:55:40 PM 02/08/2021: at async Application.compile (app.ts:983:22)
11:55:40 PM 02/08/2021: at async Application.compile (app.ts:983:22)
11:55:40 PM 02/08/2021: at async Application.init (app.ts:455:19)
11:55:40 PM 02/08/2021: at async Application.build (app.ts:239:5)
11:55:40 PM 02/08/2021: at async default (build.ts:18:3)
11:56:07 PM 02/08/2021: Error occured during the build.

**Comment by shadowtime2000** [comment]
I don't know for sure but I don't think esbuild is the best at DTS stuff

**Comment by ije** [comment]
please clear the deno cache

**Comment by ije** [comment]
https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts -> https://cdn.esm.sh/v15/@types/prop-types@15.7.3/index.d.ts

**Comment by hazae41** [comment]
> please clear the deno cache

It runs on a docker image

**Comment by hazae41** [comment]
Nevermind, I had the following line added mysteriously by VSCode

```typescript
import { string } from "https://cdn.esm.sh/v13/@types/prop-types@15.7.3/index.d.ts"
```

I removed it and it's fixed
