### ISSUE TITLE
@fullcalendar not working

### ISSUE THREAD

**Issue by evromalarkey** [postui/esm.sh#22]
https://esm.sh/@fullcalendar/daygrid fails to load, you should check all @fullcalendar plugins though, I think it's because import css statement

**Comment by ije** [comment]
@evromalarkey thanks, will fix it later

**Comment by ije** [comment]
fixed: https://esm.sh/@fullcalendar/daygrid, built css: https://esm.sh/@fullcalendar/daygrid?css
