### ISSUE TITLE
Auto Alias to Node Compat Layer

### ISSUE THREAD

**Issue by shadowtime2000** [postui/esm.sh#23]
Recently Skypack launched a feature kind of like what ESM.sh does - uses the node compat layer. Instead of having `deno bundle` stuff which needs to be committed they auto alias it to the URL to the node compat layer. I think this is a great feature as it removes the need to do chore commits to add the polyfills.

**Comment by ije** [comment]
yeah, it's in the plan to match diffenert target via UA.

**Comment by shadowtime2000** [comment]
> match diffenert target via UA

Sorry, but I don't really understand what this means? Can you clarify/expand?

**Comment by ije** [comment]
i mean the serer will check the `User-Agent` header of the request, if it is from deno client, we will use the deno.land/std/node as ployfill, or do nothing

**Comment by ije** [comment]
deno.land/std/node is not stable, so i moved back
