### ISSUE TITLE
Fix JSON error in docs

### ISSUE THREAD

**Issue by MichaelCurrin** [postui/esm.sh#24]
In Bundle Mode of README.md, I see this

```json
{
    "imports": {
        "https://esm.sh/": "https://esm.sh/[react,react-dom,swr]/",
        ...
    }
}
```

Which causes markdown error validation on `...`

You can comment this out, but JSON does not allow comments so you'll still an error.

Solution: Use `json5` syntax which supports comments.

    ```json5
    {
        "imports": {
            "https://esm.sh/": "https://esm.sh/[react,react-dom,swr]/",
            // ...
        }
    }
    ```

```json5
{
    "imports": {
        "https://esm.sh/": "https://esm.sh/[react,react-dom,swr]/",
        // ...
    }
}
```

**Comment by ije** [comment]
@MichaelCurrin thanks, i just removed the `json` lang specifier.

**Comment by MichaelCurrin** [comment]
Using `json5` will keep the syntax highlighting, which is gone now.
