### ISSUE TITLE
Anyway to get intelligence in VS code ?

### ISSUE THREAD

**Issue by ShivamJoker** [postui/esm.sh#26]
I am importing React but I am not getting any autocompletion can anyone tell me what should be project config to get it working ?

**Comment by ije** [comment]
@ShivamJoker  currently deno lsp don't suppport autocompletion yet.
fyi https://github.com/denoland/vscode_deno/issues/348

**Comment by ShivamJoker** [comment]
@ije any example of react project without using any bundlers ?

**Comment by ije** [comment]
@ShivamJoker sorry esm.sh is just a npm CDN as es module, pls google it~ thanks
