### ISSUE TITLE
Issue since change on deno polyfill

### ISSUE THREAD

**Issue by RoXuS** [postui/esm.sh#27]
Hey team,

Since change on deno polyfill (last commits) we have an issue when we use our package from esm:

![image](https://user-images.githubusercontent.com/3296671/110359672-0e3ae300-803e-11eb-80e0-37d934dd88d6.png)

Example of usages:
`export { parseStringPromise } from "https://esm.sh/xml2js@0.4.23";`

**Comment by RoXuS** [comment]
any way to stay on v15?

Something like this
`export { parseStringPromise } from "https://esm.sh/v15/xml2js@0.4.23";`

**Comment by shadowtime2000** [comment]
@RoXuS Try importing from like `https://cdn.esm.sh/v15/xml2js@0.4.23` or something like that

**Comment by RoXuS** [comment]
yeah it is ok with v15!

**Comment by RoXuS** [comment]
But we have to focus the file directly

https://cdn.esm.sh/v15/xml2js@0.4.23 -> redirect to v16
https://cdn.esm.sh/v15/xml2js@0.4.23/esnext/xml2js.js -> ok on v15

**Comment by shadowtime2000** [comment]
@ije Do you think for the time being until v16 is patched and stuff we can have esm.sh redirect to v15 and require explicit setting to use v16 with `cdn.esm.sh/v16/`?

**Comment by ije** [comment]
i will revert the **v15**'s polyfills since the deno/std/node is not stable.

**Comment by RoXuS** [comment]
> i will revert the **v15**'s polyfills since the deno/std/node is not stable.

you can't enable v15 and v16 at same time?

**Comment by ije** [comment]
i just disabled the `events` polyfill of `std/node`, please try again `deno --reload`

**Comment by RoXuS** [comment]
I get 
![image](https://user-images.githubusercontent.com/3296671/111034396-b7eeeb00-8415-11eb-8b9f-db02f3f871a6.png)

During aleph build...
