### ISSUE TITLE
can't load https://cdn.esm.sh/v15/_node_fs.js

### ISSUE THREAD

**Issue by buttercubz** [postui/esm.sh#29]
error message:
`
error: Uncaught SyntaxError: The requested module 'https://cdn.esm.sh/v15/_node_fs.js' does not provide an export named 'default' import __fs$ from "https://cdn.esm.sh/v15/_node_fs.js"; ~~~~~ at <anonymous>
`

**Comment by ije** [comment]
try `deno --reload` ?

**Comment by ije** [comment]
@buttercubz please use `https://esm.sh/...` instead of `https://cdn.esm.sh/v15/...`, since it switch to use deno `std/node` modules, after **v20** all polyills will be stored forever to get backward compatibility.
