### ISSUE TITLE
Error When Using Solid SSR

### ISSUE THREAD

**Issue by shadowtime2000** [postui/esm.sh#3]
If you go to [esm.sh/solid-ssr](https://esm.sh/solid-ssr) you get the following code:
```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: Could not resolve \"solid-ssr\" (mark it as external to exclude it from the bundle)");
export default null;
```
So basically for some reason Solid SSR doesn't work.

**Comment by ije** [comment]
the `main` field in package.json is `index.js` that dose not exist.
```json
{
  "name": "solid-ssr",
  "description": "Patches node to work with Solid's SSR",
  "version": "0.22.3",
  "main": "index.js",
  ...
}
```

<img width="540" alt="Screen Shot 2020-11-20 at 13 48 12" src="https://user-images.githubusercontent.com/2883484/99763997-09a5f980-2b37-11eb-9db7-85c2da9f3338.png">

**Comment by shadowtime2000** [comment]
Thanks @ije! Do you think that the error message could be a bit more descriptive? ("'main' field is index.js, index.js does not exist")

**Comment by ije** [comment]
nope, the message was emitted by [esbuild](https://github.com/evanw/esbuild) which i can not touch.
