### ISSUE TITLE
name export error

### ISSUE THREAD

**Issue by wleonardo** [postui/esm.sh#32]
https://esm.sh/domhandler

all name export is undefined
![image](https://user-images.githubusercontent.com/7393641/111178288-f2a77d80-85e5-11eb-8030-487876d4a9b4.png)

the problem is: name export not from domhandler.default

i think maybe we need reslove name export is from default or not

![image](https://user-images.githubusercontent.com/7393641/111179852-6b5b0980-85e7-11eb-958d-76d22bbd67df.png)

input.js like this:
![image](https://user-images.githubusercontent.com/7393641/111180019-95acc700-85e7-11eb-9655-56c96b7e4300.png)

**Comment by ije** [comment]
deployed, thanks @wleonardo 

<img width="852" alt="Screenshot 2021-03-17 at 19 56 40" src="https://user-images.githubusercontent.com/2883484/111463809-f4df1880-875a-11eb-92a0-68ea79ffe3c4.png">
