### ISSUE TITLE
named exports are missing

### ISSUE THREAD

**Issue by trusktr** [postui/esm.sh#38]
```js
import('https://esm.sh/@lume/element').then(({Element}) => {
  console.log(Element)
})
```

results in logging `undefined` instead of the expected value.

Note that the `@lume/element` package follows modern ESM standards and it works in Node.js ESM, or any tools that strictly follow Node ESM standards (like Webpack 5+).

Here's what the entry looks like: https://unpkg.com/@lume/element

**Comment by zhoukekestar** [comment]
Because esm.sh get named export by using `node` to eval your package. 
You can get more details with fellow links:
* https://github.com/postui/esm.sh/blob/master/server/build.go#L290
* https://github.com/evanw/esbuild/issues/442

And your [@lume/package/dist/LumeElement](https://unpkg.com/browse/@lume/element@0.5.4/dist/LumeElement.js)  use `window` object which will cause the eval fail.

**Comment by trusktr** [comment]
Yeah, it is a browser lib that uses `window`. 

I think if the aim is to support `ESM`, the exports should be statically extracted without having to run the module. That's the whole benefit of ESM static imports (but not `import()` function).

Random ideas: use Babel or TypeScript compilers to get an AST, then read the exports from there. That would be a more realistic way to do it I think. It would not require running any code (that can be left to the end user to decide where they will run the code).

**Comment by ije** [comment]
@trusktr thanks, yes you are right, i have a plan to rewrite the `peer.js` using AST  to get right export names, but too busy currently...in fact there was a PR #33  to try to fix this but will affect other packages so i reverted. any way i will fix it ASAP

**Comment by ije** [comment]
<img width="983" alt="Screenshot 2021-03-30 at 02 54 19" src="https://user-images.githubusercontent.com/2883484/112885348-3c728680-9103-11eb-8b2f-0e99eada10c5.png">
fixed, pls try again, thanks~
