### ISSUE TITLE
vanillajs datepicker locales doesn't work

### ISSUE THREAD

**Issue by evromalarkey** [postui/esm.sh#39]
https://esm.sh/vanillajs-datepicker/js/i18n/locales/cs.js doesn't load the locales files, I think this worked earlier - https://github.com/mymth/vanillajs-datepicker/blob/master/js/i18n/locales/cs.js

**Comment by ije** [comment]
thanks, i will fix it ASAP.

**Comment by ije** [comment]
fixed, please try again, thanks 🙏
