### ISSUE TITLE
@Apollo/client module empty

### ISSUE THREAD

**Issue by noverby** [postui/esm.sh#40]
Importing the module https://esm.sh/@apollo/client returns the empty esbuild bundle: 
https://cdn.esm.sh/v29/@apollo/client@3.3.13/esnext/client.js

Is this a bug in esm.sh or esbuild?

**Comment by ije** [comment]
seems esm.sh didn't get right export, i will look into it, thanks!

**Comment by evromalarkey** [comment]
hi @ije seems that same happend with https://cdn.esm.sh/stimulus@2.0.0/esnext/stimulus.js this worked earlier

**Comment by ije** [comment]
fixed, pls try again, thanks
