### ISSUE TITLE
Error with @material-ui/core

### ISSUE THREAD

**Issue by noverby** [postui/esm.sh#41]
With v30 https://esm.sh/@material-ui/core does not work anymore.

It returns:
```
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: No matching export in \"node_modules/@material-ui/core/esm/index.js\" for import \"default\"");
export default null;
```

**Comment by ije** [comment]
@noverby just fixed, please check again, thanks~ the latest updates get better compatibility for commonjs modules

**Comment by noverby** [comment]
Thanks @ije. Yes it fixed it, but there is still Internal Server Error's with:
* react-dom
* graphql
* @apollo/client/utilities
* @apollo/client/link/ws

**Comment by ije** [comment]
v32 fixed i guess...

**Comment by noverby** [comment]
@ije now react broke. :)

**Comment by noverby** [comment]
```
/* esm.sh - error */
throw new Error("[esm.sh] " + "json: cannot unmarshal object into Go struct field NpmPackage.versions.exports of type string");
export default null;
```

**Comment by borsemayur2** [comment]
> 
> 
> ```
> /* esm.sh - error */
> throw new Error("[esm.sh] " + "json: cannot unmarshal object into Go struct field NpmPackage.versions.exports of type string");
> export default null;
> ```

I'm getting the same error.

**Comment by FallingSnow** [comment]
Getting a similar error: no such file or directory

https://esm.sh/@fluentui/react
```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "open /tmp/esmd-build/018797da6af1b43a/node_modules/@fluentui/utilities/lib/dom/index.js: no such file or directory");
export default null;
```

**Comment by noverby** [comment]
React works now, but I'm still having issues with:
* @material-ui/data-grid
* @devexpress/dx-react-chart-material-ui

**Comment by noverby** [comment]
```
INFO Download https://esm.sh/@devexpress/dx-react-chart-material-ui
INFO Download https://esm.sh/_error.js?type=resolve&name=react-dom
ERROR Fetch module 'https://esm.sh/_error.js?type=resolve&name=react-dom': Internal Server Error
INFO Download https://esm.sh/_error.js?type=resolve&name=react-dom
ERROR Fetch module 'https://esm.sh/_error.js?type=resolve&name=react-dom': Internal Server Error
INFO Download https://esm.sh/_error.js?type=resolve&name=react-dom
ERROR Fetch module 'https://esm.sh/_error.js?type=resolve&name=react-dom': Internal Server Error
INFO Download https://esm.sh/_error.js?type=resolve&name=react-dom
ERROR Fetch module 'https://esm.sh/_error.js?type=resolve&name=react-dom': Internal Server Error
```

**Comment by ije** [comment]
@noverby  seems `@devexpress/dx-react-chart-material-ui` depends `react-dom` but did't declear it in the package.json, thanks for the detials, i will fix it asap 🙏

**Comment by ije** [comment]
fixed in `v44` branch
