### ISSUE TITLE
Suggestion - Readme

### ISSUE THREAD

**Issue by ekanna** [postui/esm.sh#43]
In Readme, change below line:

All modules are transformed to ESM by [esbuild](https://github.com/evanw/esbuild) in [NPM](http://npmjs.org/).

to

All [NPM](http://npmjs.org/) modules are transformed to ESM by [esbuild](https://github.com/evanw/esbuild).

OR 

All  modules in [NPM](http://npmjs.org/) are transformed to ESM by [esbuild](https://github.com/evanw/esbuild).

**Comment by ije** [comment]
@ekanna updated, thanks
