### ISSUE TITLE
[error]: break after update

### ISSUE THREAD

**Issue by timreichen** [postui/esm.sh#46]
https://github.com/timreichen/Bundler/issues/31: `https://esm.sh/postcss-preset-env` breaks with the newest update where in the past it didn't. Do you think there is an easy fix?

**Comment by shadowtime2000** [comment]
It seems like for some pretty popular utility packages esm.sh isn't sending the correct header for media type or something. Here is another issue related that seem to be caused by this:

[alephjs/aleph.js#253](https://github.com/alephjs/aleph.js/issues/253)

**Comment by timreichen** [comment]
@ije maybe it would be a good way to be able to specify the esm.sh version that one wants to use? For example `https://esm.sh/v27/postcss@8.2.2` with the `v27` to avoid sudden breaks? We already can do it but it will download dependencies with `v35`.

**Comment by ije** [comment]
esm.sh now have a testing page at `https://esm.sh/?test`, and i will add more edge cases to ensure each update will NOT break the previous builds.

**Comment by timreichen** [comment]
That is great. I hope you will add `typescript`, `postcss`, `posthtml`, `terser`, `csso`, `svgo`, and `postcssPresetEnv` as test cases, for now I get a completely new error, I don't know from which module:
```sh
error: Uncaught Error: [esm.sh] Unsupported nodejs builtin module "inspector"
throw new Error("[esm.sh] " + "Unsupported nodejs builtin module \"inspector\"");
      ^
    at https://cdn.esm.sh/_error.js?type=unsupported-nodejs-builtin-module&name=inspector:2:7
```

**Comment by shadowtime2000** [comment]
Stack traces which map errors to a specific module would be cool

**Comment by ije** [comment]
@shadowtime2000 now it is, the `_error.js` will point out the importer.

**Comment by ije** [comment]
@timreichen that error means it can not work in browser, even deno/std/node doesn't support the **inspector**: https://deno.land/std@0.92.0/node#experimental

**Comment by timreichen** [comment]
@ije hmm, in that case maybe postcss added that dependency lately? Because bundler used the esm postcss module without any problems until the esm update.

**Comment by ije** [comment]
@timreichen try **bundle** mode, esm.sh will wlill bundle all dependencies previously, now it will import all dependencies as url.

**Comment by timreichen** [comment]
@ije turns out it is not the `postcss` but `typescript` module that throws the error.
`https://esm.sh/typescript@4.2.4` throws 
```sh
error: Uncaught Error: [esm.sh] Unsupported nodejs builtin module "inspector" (Imported by "typescript")
throw new Error("[esm.sh] " + "Unsupported nodejs builtin module \"inspector\" (Imported by \"typescript\")");
      ^
    at https://cdn.esm.sh/_error.js?type=unsupported-nodejs-builtin-module&name=inspector&importer=typescript:2:7
```
the bundle mode version throws the same error. Why does it now where before it didn't? Maybe instead of throwing during check, it would be better to log a warning and export an empty object or a proxy which throws the error at runtime, so that the module still can be partially used?

**Comment by ije** [comment]
@timreichen i see, will add a fake polyfill for it to avoid throw an error

**Comment by ije** [comment]
<img width="818" alt="Screenshot 2021-04-12 at 00 24 47" src="https://user-images.githubusercontent.com/2883484/114312539-8efd6b00-9b25-11eb-8184-1381d2388f12.png">

@timreichen i just add the inspector polyfill, seems it can work now.

**Comment by timreichen** [comment]
Amazing, thank you! I think this might fix a lot of other errors too. Maybe it would be a good idea to add these fake polyfills for all std/node apis that are not supported (yet) by deno to have other modules partially work as well?
