### ISSUE TITLE
Panic on @material-ui/styles import

### ISSUE THREAD

**Issue by Soremwar** [postui/esm.sh#5]
Importing https://cdn.esm.sh/v9/@material-ui/styles@4.11.2/withStyles.d.ts (dependency of @material-ui/core) will result in the following

```log
/* esm.sh - error */
throw new Error("[esm.sh] " + "yarn: warning package.json: No license field\nwarning No license field\nerror An unexpected error occurred: \"https://registry.yarnpkg.com/@material-ui%2fstyles/withStyles.d.ts: Request \\\"https://registry.yarnpkg.com/@material-ui%2fstyles/withStyles.d.ts\\\" returned a 405\".\n");
export default null;
```

**Comment by ije** [comment]
@Soremwar where you get the https://cdn.esm.sh/v9/@material-ui/styles@4.11.2/withStyles.d.ts url? the right one should be https://cdn.esm.sh/v9/@material-ui/styles@4.11.2/withStyles/index.d.ts

**Comment by Soremwar** [comment]
@ije I just tried doing https://esm.sh/@material-ui/core@4.11.2?external=react@17.0.1

**Comment by Soremwar** [comment]
Something similar happens on https://esm.sh/[react,react-dom,@material-ui/core]/@material-ui/core

**Comment by ije** [comment]
@Soremwar thanks, i will fix it ASAP.

**Comment by ije** [comment]
@Soremwar please try `deno cache --reload https://esm.sh/@material-ui/core@4.11.2?external=react@17.0.1`, i just updated the server if any error outputed please do tell me, thanks

**Comment by Soremwar** [comment]
Wow that was fast

No more compile errors! Only a runtime error :( 
![image](https://user-images.githubusercontent.com/42647963/102175845-32878900-3e6e-11eb-8600-e4a1019b5c7d.png)

**Comment by ije** [comment]
most of web packages in npm don't do compatibility for deno, need time i guess...

**Comment by Soremwar** [comment]
I understand. Keep up the good work!
