### ISSUE TITLE
<!--function(a,o,s,u){return lt(e,a,o,s,u,!0)}--> when i use 'import Vue from vue'

### ISSUE THREAD

**Issue by KamiC6238** [postui/esm.sh#53]
![image](https://user-images.githubusercontent.com/23523595/115017991-e450c800-9ee9-11eb-9e51-5f651732a6fa.png)
![image](https://user-images.githubusercontent.com/23523595/115018070-fc284c00-9ee9-11eb-9327-bcd6dce0d8e8.png)
![image](https://user-images.githubusercontent.com/23523595/115018087-021e2d00-9eea-11eb-9d1f-d0fbab023621.png)

how can i make the code work?

**Comment by Miloas** [comment]
that's because `import from vue` doesn't contain comipiler

https://github.com/skypackjs/skypack-cdn/issues/78

**Comment by ije** [comment]
please check https://esm.sh/?test, vue2/vue3 can work fine.
