### ISSUE TITLE
Deno support but React

### ISSUE THREAD

**Issue by rok-star** [postui/esm.sh#54]
Hi,

Main esm.sh page shows that I can use React with Deno.
Indeed, when I create a new index.tsx file, import react from esm.sh and add a simple react component VS Code (with enabled Deno plugin) does not complain about it.

But when I add render(<App />, document.getElementById('root')) VS Code starts complaining about document symbol and offers me to include "dom" to "lib" property in tsconfig.json. So I create tsconfig.json and nothing happens... Ok, I can use // @ts-ignore...

When I run Deno.bundle it produces the code that does not run inside a browser.

So, the question is - Am I doing something wrong or it's just a dummy feature that does not actually work?

**Comment by shadowtime2000** [comment]
What is the exact code you are bundling, and what is the bundled code?

**Comment by rok-star** [comment]
I updated Deno to the latest version ```1.9```. And now everything works fine. I added ```"lib": ["dom", "ES2015"]``` to ```tsconfig.json```

![Screenshot from 2021-04-18 22-54-36](https://user-images.githubusercontent.com/3323864/115158879-19e7e380-a099-11eb-9a54-9724e215f9c5.png)

**Comment by shadowtime2000** [comment]
It might have been a bundler bug in Deno
