### ISSUE TITLE
https://esm.sh/react-color is not loading

### ISSUE THREAD

**Issue by naivefun** [postui/esm.sh#57]
cannot get response for this module

https://unpkg.com/react-color/
https://www.npmjs.com/package/react-color

**Comment by ije** [comment]
i will look into it, thanks

**Comment by ije** [comment]
now i can get the error message, seems esbuild doesn't work expectedly on linux, on macos it works fine:

```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: Could not resolve \"./_arrayEach.js\"");
export default null;
```

**Comment by talentlessguy** [comment]
imports fine in v47

can be closed, @ije

**Comment by ije** [comment]
@talentlessguy thanks
