### ISSUE TITLE
Question: What is the point of deps?

### ISSUE THREAD

**Issue by deviprsd** [postui/esm.sh#60]
The output generated in your example is pretty much the same as using `deps` than not using it. What is the point really?

https://esm.sh/swr?deps=react&dev vs https://esm.sh/swr?dev

https://www.diffchecker.com/4QPpVmy7

**Comment by fonsp** [comment]
The point is that you can specify exactly **which version** of `react` will be used by `swr` (which depends on `react`). In your example, you did not specify a version for `react`, in which case it does nothing.

Take a closer look at the example on the README. If you do not specify a react dependency version in the `swr` import, then it will load the latest compatible version of `react`, which can cause problems if you expect `react` to have a specific version.

**Comment by ije** [comment]
as @fonsp said, you need to point the `react` version or the latest will be used
