### ISSUE TITLE
502 Bad Gateway for postcss 8.1.4

### ISSUE THREAD

**Issue by stephdin** [postui/esm.sh#7]
I want to try out aleph.js [alephjs/aleph.js](https://github.com/alephjs/aleph.js), but i every time i try to start the dev server i run into the following problem:

```
error: Uncaught (in promise) TypeError: Import 'https://cdn.esm.sh/v10/postcss@8.1.4/lib/processor.js.d.ts' failed: 502 Bad Gateway
    at https://cdn.esm.sh/v10/postcss@8.1.4/lib/postcss.d.ts:22:0
```
When i check the shown links in the browser, a Cloudflare 502 Bad gateway error is returned. Every time i run the `alpeh dev` command another file is affected.

https://cdn.esm.sh/v10/postcss@8.1.4/lib/comment.js.d.ts
https://cdn.esm.sh/v10/postcss@8.1.4/lib/input.js.d.ts
https://cdn.esm.sh/v10/postcss@8.1.4/lib/processor.js.d.ts

Is this error on my end somehow? Thanks!

**Comment by stephdin** [comment]
Okay, i cleared my whole deno cache and started the aleph dev server again. Now it works. Not it fetches the files from `https://cdn.esm.sh/v11` and not `v10`. So i don't really know what happend and why. 

Feel free to close this then :)

**Comment by ije** [comment]
`alpeh dev --reload` can help, sorry for that and i will improve this to avoid new build id broken the old builds, thanks.
