### ISSUE TITLE
"Buffer.from is not a function" when using ESM package

### ISSUE THREAD

**Issue by hazae41** [postui/esm.sh#8]
Hey, I'm trying to use [web3](https://github.com/ethereum/web3.js/) from ESM

```typescript
import Web3 from "https://esm.sh/web3"

export default function Home() {
  return null;
}
```

But when loading the page I'm getting this error

```
TypeError: Buffer.from is not a function
    at varintEncode (file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:31889:23)
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:31900:37
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:69:9
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:31930:33
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:69:9
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:34701:18
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:69:9
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:34738:23
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:69:9
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:34833:23
```

**Comment by ije** [comment]
@hazae41 thanks, i will fix it ASAP.

**Comment by ije** [comment]
@hazae41 i will depoly the bugfix tmw

**Comment by hazae41** [comment]
Thanks!

**Comment by ije** [comment]
@hazae41 deployed, please try `deno cache --reload https://esm.sh/web3`

**Comment by hazae41** [comment]
Hey, it seems https://cdn.esm.sh/ is down

**Comment by ije** [comment]
<img width="1071" alt="Screen Shot 2020-12-27 at 6 35 54 PM" src="https://user-images.githubusercontent.com/2883484/103168926-61d8c580-4872-11eb-9507-1d7dd148ffad.png">

i'm not sure what happened, i will try to restart the server.

**Comment by ije** [comment]
@hazae41 fixed

**Comment by hazae41** [comment]
I have the following error when using `aleph dev` (after `aleph upgrade`)

> error: Uncaught (in promise) ReferenceError: Cannot access 'fromFileUrl14' before initialization
    at https://cdn.esm.sh/v12/_node_fs.js:363:1903

**Comment by ije** [comment]
@hazae41 sorry i didn't check the `deno bundle` output, i just reverted the `fs` polyfill, pelase try again, thanks

```bash
aleph dev --reload
```

**Comment by hazae41** [comment]
`aleph dev --reload` doesn't seem to work

![D1ADBBB2-962D-44FF-9D19-0A64C4572A86](https://user-images.githubusercontent.com/4405263/103222714-f3087480-4924-11eb-8372-6ad656533eb4.jpeg)

It just shows the same error

**Comment by ije** [comment]
please refresh the deno cache, **v0.3** will share cache with deno so `reload` option will work fine.

```bash
deno cache --reload https://deno.land/x/aleph@v0.2.27/project.ts
```

**Comment by hazae41** [comment]
It works! Thanks!

**Comment by ije** [comment]
@hazae41 thank you
