### ISSUE TITLE
deno post css error

### ISSUE THREAD

**Issue by Tindome** [postui/esm.sh#9]
Hello,

thanks for the port to Deno

I use deno version

deno 1.6.3 (release, x86_64-unknown-linux-gnu)
v8 8.8.294
typescript 4.1.3

but when i to use deno+postcss with your sample

````
import postcss from 'https://esm.sh/postcss'
import autoprefixer from 'https://esm.sh/autoprefixer'

const css = (await postcss([ autoprefixer]).process(`
    backdrop-filter: blur(5px);
    user-select: none;
`).async()).content
`````

i get the following error

error: TS2315 [ERROR]: Type 'Plugin' is not generic.
    type Autoprefixer = Plugin<Options> & ExportedAPI;
                        ~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v14/@types/autoprefixer@9.7.2/index.d.ts:65:25

do you have any idea of the origin ? thanks for helping

**Comment by shadowtime2000** [comment]
@Tindome Have you tried running it with `--no-check`? This is most likely because of incorrect typings.

**Comment by Tindome** [comment]
perfect
