### ISSUE TITLE
Error 500 got cached on Cloudflare

### ISSUE THREAD

**Issue by Nitive** [postui/esm.sh#94]
I'm getting error when I try to download file. Seems like there was a problem on a server then it was fixed but error is still cached on Cloudflare

```
curl -i 'https://cdn.esm.sh/v44/@kubernetes/client-node@0.15.0/deno/dist/gen/model/v1ServiceAccount.js'
HTTP/2 500
date: Tue, 10 Aug 2021 15:11:55 GMT
cache-control: public, max-age=31536000, immutable
cf-cache-status: HIT
age: 1531
server: cloudflare
cf-ray: 67ca28d0db65e5fc-LHR

{"error":{"status":500,"message":"open /etc/esmd/storage/builds/v44/@kubernetes/client-node@0.15.0/deno/dist/gen/model/v1ServiceAccount.js: too many open files"}}
```

Expected result: errors should not be cached or at least not a long period of time

**Comment by ije** [comment]
pls try **v45** build: https://cdn.esm.sh/v45/@kubernetes/client-node@0.15.0/deno/dist/gen/model/v1ServiceAccount.js
