### ISSUE TITLE
`/* esm.sh - error */`

### ISSUE THREAD

**Issue by roseMix** [postui/esm.sh#95]
This file gives an error:
https://cdn.esm.sh/v44/xlsx@0.17.0/types.d.ts

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "Could not resolve \"xlsx/types.d.ts\"");
export default null;
```

This gets automatically loaded from https://esm.sh/xlsx , which makes that unusable.

**Comment by ije** [comment]
@roseMix thanks, just fixed in v45 build
