### ISSUE TITLE
Video.js break after update

### ISSUE THREAD

**Issue by pionxzh** [postui/esm.sh#98]
We used [https://esm.sh/video.js@7.11.8?bundle](https://esm.sh/video.js@7.11.8?bundle) for several months, but recently (like 3~4 days ago maybe) it throw this error:
```
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: Could not resolve \"m3u8-parser\" (mark it as external to exclude it from the bundle)");
export default null;
```

At first I follow the instruction in other issues to specific the esm.sh version, but it turned out...
[https://esm.sh/v45/video.js@7.11.8?bundle](https://esm.sh/v45/video.js@7.11.8?bundle)
[https://esm.sh/v44/video.js@7.11.8?bundle](https://esm.sh/v44/video.js@7.11.8?bundle)
[https://esm.sh/v43/video.js@7.11.8?bundle](https://esm.sh/v43/video.js@7.11.8?bundle)
[https://esm.sh/v42/video.js@7.11.8?bundle](https://esm.sh/v42/video.js@7.11.8?bundle)
I couldn't find a working version.

So I try to upgrade the video.js version, found that version 7.11.0~7.12.x all broken, only version >= 7.13.0 works
[https://esm.sh/v45/video.js@7.13.0?bundle](https://esm.sh/v45/video.js@7.13.0?bundle)

I have a few questions:
1. Is this a issue from video.js? but it was work :(
2. If I specific the version with /v45/ like this, will it promised to be always working the same?
3. If answer of 2 is no, any other recommandation for this?

**Comment by ije** [comment]
@pionxzh thanks, i will fix this later.
as you can see https://cdn.esm.sh/v45/video.js@VERSION/TARGET/video.bundle.js is fixed for build that is the real CDN URL. 
i will add a `?buildVersion` to allow you downgrade to the old builds!

**Comment by ije** [comment]
just fixed, sorry i missed something in v45 updates

**Comment by pionxzh** [comment]
Thanks for fixing it so quickly, is it possible to have a test case for this? Or is it a edge case?

**Comment by ije** [comment]
i didn't test the module, but the build is working as expected
